export const sliderItems = [
	{
		id: 1,
		img: "https://i.ibb.co/dMyHvr9/slider-1.png",
		title: "Sale 1",
		description: "Description 1",
		bg: "f5fafd",
	},
	{
		id: 2,
		img: "https://i.ibb.co/BKcBHzB/slider-2.png",
		title: "Sale 2",
		description: "Description 2",
		bg: "fcf1ed",
	},
	{
		id: 3,
		img: "https://i.ibb.co/jwhgCrR/slider-3.png",
		title: "Sale 3",
		description: "Description 3",
		bg: "fbf0f4",
	},
];

export const categories = [
	{
		id: 1,

		image: "https://i.ibb.co/mJPRC65/Seating.png",
		title: "Seating",
		subCategory: ["Sofas", "Chairs", "Ottomans and Poufs"],
	},
	{
		id: 2,
		image: "https://i.ibb.co/S76K9T8/Tables.png",
		title: "Tables",
		subCategory: ["Coffee Tables", "Dining Tables", "End Tables"],
	},
	{
		id: 3,
		image: "https://i.ibb.co/qYhhZmP/Storage.png",
		title: "Storage",
		subCategory: ["Bookshelves", "Cabinets", "Dressers and Chests"],
	},
	{
		id: 4,
		image: "https://i.ibb.co/vhZP78C/Bedroom.png",
		title: "Bedroom Furniture",
		subCategory: ["Bed Frames", "Nightstands", "Wardrobes"],
	},
	{
		id: 5,
		image: "https://i.ibb.co/KG9h1W1/Outdoor.png",
		title: "Outdoor Furniture",
		subCategory: ["Patio Sets", "Sun Loungers", "Outdoor Sofas"],
	},
];

export const products = [
	{
		name: "Chesterfield Sofa",
		category: "Seating",
		subCategory: "Sofas",
		trending: true,
		price: 999.99,
		description:
			"Introducing our Chesterfield Sofa, a timeless piece of furniture that exudes sophistication and charm. Crafted with meticulous attention to detail, this sofa features classic rolled arms and deep button tufting for a traditional look. Its luxurious upholstery adds elegance to any living space, while the spacious seating area ensures comfort for hours of relaxation. Whether placed in a formal living room or a cozy den, this sofa effortlessly elevates the ambiance of your home.",

		image: "https://i.ibb.co/jRWYptF/Chesterfield-Sofa.jpg",
		id: 1,
		Rating: 4.6,
	},
	{
		name: "Sectional Sofa with Chaise",
		category: "Seating",
		subCategory: "Sofas",
		trending: false,
		price: 1500,
		description:
			"Introducing our Sectional Sofa with Chaise, a versatile and stylish addition to your living space. Designed for modern comfort, this sectional sofa features a spacious chaise lounge perfect for lounging or napping. With its plush cushions and supportive backrest, it offers optimal comfort for relaxing with family and friends. The modular design allows you to customize the layout to suit your space, making it ideal for small apartments or large living rooms. Elevate your home with the contemporary flair and comfort of our sectional sofa.",

		// image: `${process.env.PUBLIC_URL}/images/Sofas/Sectional_Sofa_with_Chaise.jpeg`,
		image: "https://i.ibb.co/QcVKkbP/Sectional-Sofa-with-Chaise.jpg",
		id: 2,
		Rating: 4.1,
	},
	{
		name: "Mid-Century Modern Sofa",
		category: "Seating",
		subCategory: "Sofas",
		trending: false,
		price: 900,
		description:
			"Introducing our Mid-Century Modern Sofa, a sleek and stylish centerpiece for your living room. Inspired by iconic designs of the 1950s and 1960s, this sofa features clean lines, tapered legs, and a minimalist silhouette. Crafted with high-quality materials and upholstered in soft fabric, it offers both comfort and sophistication. Whether hosting guests or lounging with a book, this sofa adds a touch of retro charm to any space. Embrace the timeless appeal of mid-century modern design with our stylish sofa.",
		// image: `${process.env.PUBLIC_URL}/images/Sofas/Mid-Century_Modern_Sofa.jpeg`,
		image: "https://i.ibb.co/H2mPG8P/Mid-Century-Modern-Sofa.jpg",
		id: 3,
		Rating: 3.9,
	},
	{
		name: "Leather Reclining Sofa",
		category: "Seating",
		subCategory: "Sofas",
		trending: true,
		price: 1800,
		description:
			"Introducing our Leather Reclining Sofa, the epitome of luxury and comfort. Crafted with premium leather upholstery, this sofa exudes sophistication and durability. The plush cushions and padded armrests provide unparalleled support, while the reclining feature allows you to relax with ease. Whether watching TV or enjoying a quiet evening, this sofa offers the perfect combination of style and functionality. Elevate your living space with the timeless elegance of our leather reclining sofa.",
		// image: `${process.env.PUBLIC_URL}/images/Sofas/Leather_Reclining_Sofa.jpeg`,
		image: "https://i.ibb.co/mGVnzLg/Leather-Reclining-Sofa.jpg",
		id: 4,
		Rating: 4.8,
	},
	{
		name: "Sleeper Sofa with Pull-Out Bed",
		category: "Seating",
		subCategory: "Sofas",
		trending: false,
		price: 1300,
		description:
			"Introducing our Sleeper Sofa with Pull-Out Bed, the perfect blend of style and functionality. This versatile sofa features a convenient pull-out bed, making it ideal for accommodating overnight guests. Crafted with durable materials and plush cushions, it offers both comfort and support for lounging or sleeping. Whether used in a small apartment or a guest room, this sleeper sofa provides a cozy spot for relaxation and a comfortable bed for overnight stays. Transform your living space with the practicality and comfort of our sleeper sofa.",
		// image: `${process.env.PUBLIC_URL}/images/Sofas/Sleeper_Sofa_with_Pull-Out_Bed.png`,
		image: "https://i.ibb.co/br5VwPY/Sleeper-Sofa-with-Pull-Out-Bed.png",
		id: 5,
		Rating: 4.5,
	},
	{
		name: "Wingback Accent Chair",
		category: "Seating",
		subCategory: "Chairs",
		trending: false,
		price: 400,
		description:
			"Introducing our Wingback Accent Chair, a timeless piece that adds elegance to any room. With its classic design and high back, this chair offers both style and comfort. Crafted with sturdy materials and upholstered in soft fabric, it provides a cozy spot for relaxation. Whether placed in a reading nook or as a statement piece in the living room, this accent chair brings a touch of sophistication to your home decor.",
		// image: `${process.env.PUBLIC_URL}/images/Chairs/Wingback_Accent_Chair.png`,
		image: "https://i.ibb.co/kyr5kRk/Wingback-Accent-Chair.png",
		id: 6,
		Rating: 4,
	},
	{
		name: "Eames Lounge Chair",
		category: "Seating",
		subCategory: "Chairs",
		trending: false,
		price: 2000,
		description:
			"Meet our Eames Lounge Chair, an icon of modern design and comfort. Inspired by mid-century aesthetics, this chair features a molded plywood shell and premium leather upholstery, offering both style and luxury. With its ergonomic design and plush cushions, it provides exceptional comfort for relaxation. Whether placed in a living room or study, this lounge chair exudes sophistication and timeless elegance.",
		// image: `${process.env.PUBLIC_URL}/images/Chairs/Eames_Lounge_Chair.png`,
		image: "https://i.ibb.co/4SbKH16/Eames-Lounge-Chair.png",
		id: 7,
		Rating: 3.7,
	},
	{
		name: "Upholstered Club Chair",
		category: "Seating",
		subCategory: "Chairs",
		trending: true,
		price: 300,
		description:
			"Introducing our Upholstered Club Chair, a cozy and inviting addition to any space. With its classic design and plush cushions, this chair offers both comfort and style. Crafted with durable upholstery and sturdy legs, it provides a perfect spot for relaxation. Whether used in a living room corner or as part of a seating arrangement, this club chair brings warmth and charm to your home.",
		// image: `${process.env.PUBLIC_URL}/images/Chairs/Upholstered_Club_Chair.png`,
		image: "https://i.ibb.co/GcjyL1W/Upholstered-Club-Chair.png",
		id: 8,
		Rating: 4.7,
	},
	{
		name: "Swivel Glider Recliner",
		category: "Seating",
		subCategory: "Chairs",
		trending: false,
		price: 500,
		description:
			"Introducing our Swivel Glider Recliner, a versatile and comfortable chair for your home. With its swivel and glider base, this chair offers smooth movement in any direction, perfect for relaxation. Crafted with plush cushions and a reclining feature, it provides optimal support for lounging. Whether placed in a nursery or living room, this swivel glider recliner offers both style and functionality.",
		// image: `${process.env.PUBLIC_URL}/images/Chairs/Swivel_Glider_Recliner.jpeg`,
		image: "https://i.ibb.co/cyN91bq/Swivel-Glider-Recliner.jpg",
		id: 9,
		Rating: 4.6,
	},
	{
		name: "Papasan Chair",
		category: "Seating",
		subCategory: "Chairs",
		trending: false,
		price: 200,
		description:
			"Meet our Papasan Chair, a cozy and whimsical addition to any room. Crafted with a sturdy rattan frame and a plush cushion, this chair offers both comfort and style. Its deep, bowl-shaped seat provides a snug spot for relaxation, perfect for reading or lounging. Whether placed in a living room corner or bedroom, this Papasan Chair brings a relaxed vibe and bohemian charm to your home.",
		// image: `${process.env.PUBLIC_URL}/images/Chairs/Papasan_Chair.jpeg`,
		image: "https://i.ibb.co/ZNNYG6S/Papasan-Chair.jpg",
		id: 10,
		Rating: 4.3,
	},
	{
		name: "Round Leather Ottoman",
		category: "Seating",
		subCategory: "Ottomans and Poufs",
		trending: true,
		price: 250,
		description:
			"Introducing our Round Leather Ottoman, a versatile and stylish piece for your living space. Crafted with durable leather upholstery and a sturdy frame, this ottoman offers both comfort and functionality. Its round shape and compact size make it perfect for use as a footrest or extra seating. Whether placed in a living room or bedroom, this leather ottoman adds a touch of sophistication to any decor.",
		// image: `${process.env.PUBLIC_URL}/images/Ottomans_and_Poufs/Round_Leather_Ottoman.jpeg`,
		image: "https://i.ibb.co/31XDRmR/Round-Leather-Ottoman.jpg",
		id: 11,
		Rating: 4.8,
	},
	{
		name: "Fabric Storage Ottoman",
		category: "Seating",
		subCategory: "Ottomans and Poufs",
		trending: false,
		price: 150,
		description:
			"Meet our Fabric Storage Ottoman, a practical and stylish addition to your home. Crafted with durable fabric upholstery and a sturdy frame, this ottoman offers both comfort and storage. Its spacious compartment provides ample space for stashing blankets, pillows, or other essentials, helping you keep your space neat and organized. Whether used as a footrest or extra seating, this fabric ottoman adds versatility to any room.",
		// image: `${process.env.PUBLIC_URL}/images/Ottomans_and_Poufs/Fabric_Storage_Ottoman.jpeg`,
		image: "https://i.ibb.co/7ysCLXp/Fabric-Storage-Ottoman.jpg",
		id: 12,
		Rating: 4,
	},
	{
		name: "Moroccan Pouf",
		category: "Seating",
		subCategory: "Ottomans and Poufs",
		trending: true,
		price: 130,
		description:
			"Introducing our Moroccan Pouf, a charming and versatile addition to your living space. Handcrafted with genuine leather and adorned with traditional Moroccan-inspired stitching, this pouf exudes exotic elegance and bohemian flair. Its compact size makes it perfect for use as a footrest or extra seating. Whether placed in a living room or bedroom, this Moroccan pouf adds a touch of cultural charm and cozy comfort to any decor.",
		// image: `${process.env.PUBLIC_URL}/images/Ottomans_and_Poufs/Moroccan_Pouf.jpeg`,
		image: "https://i.ibb.co/1n14K9j/Moroccan-Pouf.jpg",
		id: 13,
		Rating: 4.8,
	},
	{
		name: "Tufted Square Ottoman",
		category: "Seating",
		subCategory: "Ottomans and Poufs",
		trending: false,
		price: 180,
		description:
			"Meet our Tufted Square Ottoman, a chic and versatile addition to your home. Crafted with luxurious fabric upholstery and featuring elegant tufted detailing, this ottoman exudes sophistication. Its square shape and compact size make it perfect for use as a footrest or extra seating. Whether placed in a living room or bedroom, this tufted ottoman adds a touch of elegance and comfort to any space.",
		// image: `${process.env.PUBLIC_URL}/images/Ottomans_and_Poufs/Tufted_Square_Ottoman.jpeg`,
		image: "https://i.ibb.co/72jCxsC/Tufted-Square-Ottoman.jpg",
		id: 14,
		Rating: 4.5,
	},
	{
		name: "Glass Top Coffee Table",
		category: "Tables",
		subCategory: "Coffee Tables",
		trending: false,
		price: 300,
		description:
			"Introducing our Glass Top Coffee Table, a sleek and modern centerpiece for your living room. Crafted with a sturdy metal or wooden base and featuring a clear tempered glass top, this coffee table exudes contemporary elegance. The transparent glass top creates a sense of openness, while the minimalist design adds versatility to any decor style. Whether hosting gatherings or displaying decorative accents, this coffee table is sure to elevate your living space with its stylish design.",
		// image: `${process.env.PUBLIC_URL}/images/Tables/Glass_Top_Coffee_Table.jpeg`,
		image: "https://i.ibb.co/rQ4jN3k/Glass-Top-Coffee-Table.jpg",
		id: 15,
		Rating: 4.7,
	},
	{
		name: "Rustic Wood Coffee Table",
		category: "Tables",
		subCategory: "Coffee Tables",
		trending: false,
		price: 350,
		description:
			"Introducing our Rustic Wood Coffee Table, a charming addition to your living space. Crafted with solid wood and featuring a distressed finish, this coffee table exudes rustic charm. Its sturdy construction and spacious tabletop make it perfect for holding drinks, snacks, and decorative accents. Whether placed in a cozy cabin or a modern farmhouse, this coffee table adds warmth and character to any decor style.",
		// image: `${process.env.PUBLIC_URL}/images/Tables/Rustic_Wood_Coffee_Table.jpeg`,
		image: "https://i.ibb.co/Pt12qky/Rustic-Wood-Coffee-Table.jpg",
		id: 16,
		Rating: 4.2,
	},
	{
		name: "Marble and Metal Coffee Table",
		category: "Tables",
		subCategory: "Coffee Tables",
		trending: false,
		price: 500,
		description:
			"Introducing our Marble and Metal Coffee Table, a luxurious centerpiece for your living room. Crafted with a sleek metal frame and featuring a stunning marble tabletop, this coffee table exudes contemporary elegance. The juxtaposition of materials adds visual interest and texture, while the spacious surface provides ample space for displaying decorative accents or serving drinks and snacks. Whether placed in a modern or eclectic space, this coffee table is sure to elevate your decor with its sophisticated design.",
		// image: `${process.env.PUBLIC_URL}/images/Ottomans_and_Poufs/Tufted_Square_Ottoman.jpeg`,
		image: "https://i.ibb.co/zr4b2xV/Marble-and-Metal-Coffee-Table.jpg",
		id: 17,
		Rating: 4.6,
	},

	{
		name: "Lift-Top Coffee Table",
		category: "Tables",
		subCategory: "Coffee Tables",
		trending: false,
		price: 450,
		description:
			"Introducing our Lift-Top Coffee Table, a versatile and functional addition to your living room. Crafted with a sturdy wood frame, this coffee table features a convenient lift-top mechanism that raises to create a comfortable workspace or dining area. The spacious storage compartment beneath the tabletop provides ample space for stashing blankets, board games, or other essentials, helping you keep your space neat and organized. Whether used for working, dining, or relaxing, this lift-top coffee table offers both style and practicality for your home.",
		// image:"",
		image: "https://i.ibb.co/m6PWVdn/Lift-Top-Coffee-Table.jpg",
		id: 18,
		Rating: 3.5,
	},
	{
		name: "Rectangular Farmhouse Dining Table",
		category: "Tables",
		subCategory: "Dining Tables",
		trending: false,
		price: 700,
		description:
			"Meet our Rectangular Farmhouse Dining Table, a charming and inviting addition to your dining room. Crafted with solid wood and featuring a distressed finish, this dining table exudes rustic charm. Its spacious tabletop provides ample room for family gatherings, and the sturdy construction ensures durability. The classic farmhouse design and clean lines make it a versatile addition to any decor style, adding warmth and character to your dining space.",
		// image:"",
		image: "https://i.ibb.co/6wkK7K0/Rectangular-Farmhouse-Dining-Table.jpg",
		id: 19,
		Rating: 3.9,
	},
	{
		name: "Round Pedestal Dining Table",
		category: "Tables",
		subCategory: "Dining Tables",
		trending: true,
		price: 600,
		description:
			"Introducing our Round Pedestal Dining Table, a stylish and space-saving option for your dining area. Crafted with a sturdy pedestal base and featuring a round tabletop, this dining table exudes classic elegance. Its compact size makes it perfect for smaller dining spaces or breakfast nooks, while the pedestal design allows for comfortable seating around the table without the obstruction of table legs. The timeless design and versatile appeal make it a perfect fit for any decor style, adding a touch of sophistication to your dining room.		",
		// image:"",
		image: "https://i.ibb.co/FYwmngv/Round-Pedestal-Dining-Table.jpg",
		id: 20,
		Rating: 4.7,
	},
	{
		name: "Glass Top Dining Table",
		category: "Tables",
		subCategory: "Dining Tables",
		trending: false,
		price: 800,
		description:
			"Introducing our Glass Top Dining Table, a sleek and modern addition to your dining space. Crafted with a sturdy metal or wooden base and featuring a clear tempered glass top, this dining table exudes contemporary elegance. The transparent glass top creates a sense of openness and lightness, while the sleek lines and minimalist design make it a versatile addition to any decor style. Whether hosting formal dinner parties or casual family meals, this dining table provides the perfect backdrop for sharing food and conversation with loved ones.",
		image: "https://i.ibb.co/kgkjcVB/Glass-Top-Dining-Table.png",
		id: 21,
		Rating: 4.4,
	},
	{
		name: "Extendable Trestle Dining Table",
		category: "Tables",
		subCategory: "Dining Tables",
		trending: false,
		price: 900,
		description:
			"Introducing our Extendable Trestle Dining Table, a versatile and practical addition to your dining room. Crafted with a sturdy trestle base and featuring a spacious tabletop, this dining table offers ample room for family gatherings and dinner parties. The extendable design allows you to easily adjust the table's length to accommodate extra guests, making it ideal for entertaining. Whether used for everyday meals or special occasions, this dining table combines functionality with timeless elegance, adding a touch of sophistication to your home.",
		image: "https://i.ibb.co/vmLKW0Z/Extendable-Trestle-Dining-Table.png",
		id: 22,
		Rating: 4.3,
	},

	{
		name: "C-Shaped End Table",
		category: "Tables",
		subCategory: "End Tables",
		trending: false,
		price: 130,
		description:
			"Introducing our C-Shaped End Table, a sleek and space-saving addition to your living room or bedroom. Crafted with a sturdy metal frame and featuring a C-shaped design, this end table slides effortlessly under sofas or beds, providing a convenient surface for drinks, snacks, or electronic devices. Its minimalist silhouette and versatile functionality make it perfect for small spaces or as a stylish accent piece in any room. Elevate your decor with the modern flair and practicality of our C-shaped end table.",
		image: "https://i.ibb.co/xMf1zc6/C-Shaped-End-Table.jpg",
		id: 23,
		Rating: 4.1,
	},
	{
		name: "Nesting End Tables",
		category: "Tables",
		subCategory: "End Tables",
		trending: false,
		price: 200,
		description:
			"Introducing our Nesting End Tables, a versatile and space-saving solution for your living space. Crafted with sturdy metal frames and featuring sleek wooden tops, these end tables offer both style and functionality. The nesting design allows you to tuck the smaller table neatly under the larger one when not in use, making them perfect for small spaces or as flexible accents in larger rooms. Whether used together or separately, these nesting end tables add a touch of contemporary elegance to any decor.",
		image: "https://i.ibb.co/kKF1LS7/Nesting-End-Tables.jpg",
		id: 24,
		Rating: 4.2,
	},
	{
		name: "Drum Shaped End Table",
		category: "Tables",
		subCategory: "End Tables",
		trending: false,
		price: 150,
		description:
			"Introducing our Drum Shaped End Table, a unique and stylish addition to your living space. Crafted with a sturdy metal base and featuring a drum-shaped silhouette, this end table adds a touch of modern flair to any room. Its compact size makes it perfect for use as a side table or accent piece, while the spacious tabletop provides ample space for drinks, books, or decorative accents. Whether placed next to a sofa or beside a bed, this drum-shaped end table brings a sense of contemporary elegance to your home decor.",
		image: "https://i.ibb.co/jwm99wP/Drum-Shaped-End-Table.png",
		id: 25,
		Rating: 3.8,
	},
	{
		name: "Hexagon Side Table",
		category: "Tables",
		subCategory: "End Tables",
		trending: true,
		price: 80,
		description:
			"Introducing our Hexagon Side Table, a chic and modern accent for your living space. Crafted with a sleek metal frame and featuring a hexagonal tabletop, this side table adds geometric interest to any room. Its compact size makes it perfect for use as an end table or plant stand, while the open base creates a sense of lightness and space. Whether placed next to a sofa or beside a chair, this hexagon side table adds a touch of contemporary style to your home decor.",
		image: "https://i.ibb.co/vvHndcB/Hexagon-Side-Table-End-Table.png",
		id: 26,
		Rating: 4.8,
	},
	{
		name: "Mirrored Accent Table",
		category: "Tables",
		subCategory: "End Tables",
		trending: false,
		price: 130,
		description:
			"Introducing our Mirrored Accent Table, a glamorous and elegant addition to your living space. Crafted with a sleek metal frame and featuring mirrored surfaces, this accent table exudes sophistication and style. Its compact size makes it perfect for use as an end table or nightstand, while the mirrored finish adds a touch of luxury to any room. Whether placed next to a sofa or beside a bed, this mirrored accent table adds a touch of Hollywood regency flair to your home decor.",
		image: "https://i.ibb.co/jJyn6D0/Mirrored-Accent-End-Table.png",
		id: 27,
		Rating: 3.2,
	},
	{
		name: "Tall Wooden Bookshelf",
		category: "Storage",
		subCategory: "Bookshelves",
		trending: true,
		price: 300,
		description:
			"Introducing our Tall Wooden Bookshelf, a functional and stylish storage solution for your home. Crafted with sturdy wood and featuring multiple shelves, this bookshelf offers ample space for organizing books, decor, and more. Its tall design maximizes vertical space, making it perfect for small rooms or narrow spaces. Whether placed in a living room, home office, or bedroom, this tall bookshelf adds both storage and visual interest to any room.",
		image: "https://i.ibb.co/DbQ4mVN/Tall-Wooden-Bookshelf.png",
		id: 28,
		Rating: 4.9,
	},
	{
		name: "Corner Bookcase",
		category: "Storage",
		subCategory: "Bookshelves",
		trending: false,
		price: 200,
		description:
			"Introducing our Corner Bookcase, a space-saving storage solution for your home. Crafted with sturdy wood and featuring a triangular design, this bookcase fits neatly into corners, maximizing unused space. Its multiple shelves provide ample room for organizing books, decor, and other items, while the open design adds visual interest to any room. Whether placed in a living room, home office, or bedroom, this corner bookcase adds both functionality and style to your home decor.",
		image: "https://i.ibb.co/8YNymRz/Corner-Bookcase.jpg",
		id: 29,
		Rating: 4.2,
	},
	{
		name: "Ladder Shelf",
		category: "Storage",
		subCategory: "Bookshelves",
		trending: false,
		price: 150,
		description:
			"Introducing our Ladder Shelf, a versatile and stylish storage solution for your home. Crafted with sturdy wood and featuring a ladder-like design, this shelf leans against the wall, saving valuable floor space. Its multiple shelves of varying sizes provide ample room for organizing books, decor, and other items, while the ladder design adds a touch of modern flair to any room. Whether placed in a living room, home office, or bedroom, this ladder shelf adds both functionality and visual interest to your home decor.",
		image: "https://i.ibb.co/n1Cw9Lc/Ladder-Shelf.jpg",
		id: 30,
		Rating: 4.4,
	},
	{
		name: "Industrial Pipe Bookshelf",
		category: "Storage",
		subCategory: "Bookshelves",
		trending: false,
		price: 250,
		description:
			"Introducing our Industrial Pipe Bookshelf, a rugged and distinctive storage solution for your home. Crafted with durable metal pipes and rustic wood shelves, this bookshelf combines industrial charm with practicality. Its open design and sturdy construction make it perfect for displaying books, decor, and other items in your living room, office, or bedroom. Whether you're a fan of the industrial aesthetic or looking to add a unique touch to your space, this pipe bookshelf is sure to make a statement.",
		image: "https://i.ibb.co/HKF6BLc/Industrial-Pipe-Bookshelf.jpg",
		id: 31,
		Rating: 4.6,
	},
	{
		name: "Cube Storage Organizer",
		category: "Storage",
		subCategory: "Bookshelves",
		trending: false,
		price: 100,
		description:
			"Introducing our Cube Storage Organizer, a versatile and functional addition to your home. Crafted with sturdy wood and featuring multiple cubbies, this organizer offers ample space for storing books, toys, decor, and more. Its modular design allows you to customize the layout to suit your needs, whether you need open shelves or concealed storage. Whether placed in a living room, playroom, or bedroom, this cube organizer adds both style and organization to your space.",
		image: "https://i.ibb.co/ZV6ZRjH/Cube-Storage-Organizer.jpg",
		id: 32,
		Rating: 4.4,
	},
	{
		name: "Modern Media Cabinet",
		category: "Storage",
		subCategory: "Cabinets",
		trending: true,
		price: 500,
		description:
			"Introducing our Modern Media Cabinet, a sleek and practical storage solution for your entertainment essentials. Crafted with sturdy wood and featuring clean lines and minimalist design, this cabinet offers both style and functionality. Its spacious shelves and drawers provide ample storage for media devices, DVDs, and other items, while the sleek finish adds a touch of contemporary elegance to any room. Whether used in a living room or entertainment center, this modern media cabinet is sure to enhance your space with its versatile design.",
		image: "https://i.ibb.co/CbdkPVG/Modern-Media-Cabinet.jpg",
		id: 33,
		Rating: 4.7,
	},
	{
		name: "Display Cabinet with Glass Doors",
		category: "Storage",
		subCategory: "Cabinets",
		trending: false,
		price: 600,
		description:
			"Introducing our Display Cabinet with Glass Doors, a stylish and practical storage solution for showcasing your favorite items. Crafted with sturdy wood and featuring glass doors, this cabinet allows you to display books, collectibles, and decor while keeping them protected from dust and damage. Its adjustable shelves provide customizable storage options, while the elegant design adds a touch of sophistication to any room. Whether used in a living room, dining room, or home office, this display cabinet adds both beauty and functionality to your space.",
		image: "https://i.ibb.co/3RJ1sJR/Display-Cabinet-with-Glass-Doors.jpg",
		id: 34,
		Rating: 4.3,
	},
	{
		name: "Shoe Storage Cabinet",
		category: "Storage",
		subCategory: "Cabinets",
		trending: false,
		price: 200,
		description:
			"Introducing our Shoe Storage Cabinet, a practical and space-saving solution for organizing your footwear. Crafted with sturdy wood and featuring multiple shelves or compartments, this cabinet offers ample space for storing shoes, keeping them neat and organized. Its compact design makes it perfect for entryways, hallways, or closets, while the sleek finish adds a touch of modern elegance to any space. Whether you have a large collection of shoes or just need a convenient place to store your everyday pairs, this shoe storage cabinet is sure to meet your needs with style ",
		image: "https://i.ibb.co/yf7dCTP/Shoe-Storage-Cabinet.jpg",
		id: 35,
		Rating: 4.2,
	},
	{
		name: "Bathroom Linen Tower",
		category: "Storage",
		subCategory: "Cabinets",
		trending: true,
		price: 300,
		description:
			"Introducing our Bathroom Linen Tower, a versatile and functional storage solution for your bathroom essentials. Crafted with sturdy wood and featuring multiple shelves or compartments, this tower offers ample space for storing towels, toiletries, and other bathroom items. Its tall and narrow design makes it perfect for maximizing vertical space in small bathrooms, while the sleek finish adds a touch of elegance to any decor. Whether used to complement a traditional or modern bathroom, this linen tower adds both style and organization to your space.",
		image: "https://i.ibb.co/Qmq6rcN/Bathroom-Linen-Tower.jpg",
		id: 36,
		Rating: 4.9,
	},
	{
		name: "6-Drawer Mid-Century Dresser",
		category: "Storage",
		subCategory: "Dressers and Chests",
		trending: false,
		price: 500,
		description:
			"Introducing our 6-Drawer Mid-Century Dresser, a stylish and functional addition to your bedroom. Crafted with durable wood and featuring a sleek mid-century design, this dresser offers ample storage space for clothing, accessories, and more. Its six spacious drawers glide smoothly on metal runners, providing easy access to your belongings. The minimalist silhouette and tapered legs add a touch of retro charm to any bedroom decor. Whether used alone or paired with other mid-century furniture pieces, this dresser brings both style and organization to your space.",
		image: "https://i.ibb.co/N9bdYQC/6-Drawer-Mid-Century-Dresser.jpg",
		id: 37,
		Rating: 4.6,
	},
	{
		name: "High Gloss White Chest of Drawers",
		category: "Storage",
		subCategory: "Dressers and Chests",
		trending: false,
		price: 600,
		description:
			"Introducing our High Gloss White Chest of Drawers, a sleek and modern storage solution for your bedroom. Crafted with a durable wood frame and featuring a high gloss white finish, this chest of drawers exudes contemporary elegance. Its spacious drawers provide ample storage space for clothing, bedding, and other items, while the glossy finish adds a touch of sophistication to any decor. The minimalist design and clean lines make it a versatile addition to any bedroom style, whether modern or minimalist. Elevate your bedroom decor with the sleek and stylish appeal of our high gloss white chest of drawers.",
		image: "https://i.ibb.co/R7Sy40p/High-Gloss-White-Chest-of-Drawers.jpg",
		id: 38,
		Rating: 4.7,
	},
	{
		name: "Mirrored Accent Chest",
		category: "Storage",
		subCategory: "Dressers and Chests",
		trending: false,
		price: 700,
		description:
			"Introducing our Mirrored Accent Chest, a glamorous and functional storage solution for your bedroom. Crafted with a sturdy wood frame and featuring mirrored panels, this accent chest adds a touch of luxury to any space. Its spacious drawers provide ample storage for clothing, linens, and other items, while the mirrored finish reflects light and creates a sense of openness. Whether used as a standalone piece or paired with other mirrored furniture, this accent chest adds elegance and sophistication to your bedroom decor.",
		image: "https://i.ibb.co/KqQswHt/Mirrored-Accent-Chest.png",
		id: 39,
		Rating: 4,
	},
	{
		name: "Kids' 3-Drawer Dresser",
		category: "Storage",
		subCategory: "Dressers and Chests",
		trending: false,
		price: 250,
		description:
			"Introducing our Kids' 3-Drawer Dresser, a charming and practical storage solution for your child's bedroom. Crafted with durable wood and featuring a child-friendly design, this dresser offers three spacious drawers for storing clothing, toys, and other essentials. Its compact size makes it perfect for smaller spaces, while the rounded edges and smooth finish ensure safety for young children. Whether used alone or paired with other kids' furniture, this dresser adds both style and organization to your child's room.",
		image: "https://i.ibb.co/2tkHfCp/Kids-3-Drawer-Dresser.png",
		id: 40,
		Rating: 4,
	},
	{
		name: "Upholstered Platform Bed",
		category: "Bedroom Furniture",
		subCategory: "Bed Frames",
		trending: false,
		price: 700,
		description:
			"Introducing our Upholstered Platform Bed, a luxurious and stylish centerpiece for your bedroom. Crafted with a sturdy wooden frame and upholstered in soft fabric, this platform bed exudes comfort and sophistication. Its sleek and minimalist design adds a touch of modern elegance to any bedroom decor, while the sturdy slat support system ensures durability and stability. Whether you prefer a cozy retreat or a contemporary oasis, this upholstered platform bed provides the perfect foundation for a restful night's sleep.",
		image: "https://i.ibb.co/3S4F903/Upholstered-Platform-Bed.png",
		id: 41,
		Rating: 4.4,
	},
	{
		name: "Sleigh Bed with Storage Drawers",
		category: "Bedroom Furniture",
		subCategory: "Bed Frames",
		trending: false,
		price: 900,
		description:
			"Introducing our Sleigh Bed with Storage Drawers, a stylish and functional addition to your bedroom. Crafted with a classic sleigh bed design and featuring built-in storage drawers, this bed offers both elegance and practicality. Its sturdy wooden frame ensures durability, while the integrated drawers provide convenient storage for extra bedding or clothing. Upgrade your bedroom with this timeless piece that combines style and functionality seamlessly.",
		image: "https://i.ibb.co/k6zyDsn/Sleigh-Bed-with-Storage-Drawers.png",
		id: 42,
		Rating: 4.1,
	},
	{
		name: "Canopy Bed Frame",
		category: "Bedroom Furniture",
		subCategory: "Bed Frames",
		trending: false,
		price: 800,
		description:
			"Introducing our Canopy Bed Frame, a statement piece for your bedroom. Crafted with a sturdy metal or wooden frame, this bed features a classic canopy design that adds elegance and drama to any space. Its sleek and minimalist silhouette offers a modern twist on traditional canopy beds, while the sturdy construction ensures durability and stability. Whether you're creating a romantic retreat or a cozy haven, this canopy bed frame provides the perfect foundation for a stylish and comfortable bedroom.",
		image: "https://i.ibb.co/0J4kZqH/Canopy-Bed-Frame.png",
		id: 43,
		Rating: 4.6,
	},
	{
		name: "Metal Bed Frame with Headboard",
		category: "Bedroom Furniture",
		subCategory: "Bed Frames",
		trending: false,
		price: 300,
		description:
			"Introducing our Metal Bed Frame with Headboard, a sleek and modern addition to your bedroom. Crafted with durable metal, this bed frame features a stylish headboard that adds both comfort and style to your space. Its minimalist design and sturdy construction make it perfect for contemporary bedrooms, while the metal slats provide ample support and stability for your mattress. Upgrade your sleeping sanctuary with this chic and functional metal bed frame.",
		image: "https://i.ibb.co/WpWfxSh/Metal-Bed-Frame-with-Headboard.jpg",
		id: 44,
		Rating: 4.6,
	},
	{
		name: "Tufted Velvet Bed",
		category: "Bedroom Furniture",
		subCategory: "Bed Frames",
		trending: false,
		price: 1000,
		description:
			"Introducing our Tufted Velvet Bed, a luxurious centerpiece for your bedroom. Crafted with a sturdy wooden frame and upholstered in plush velvet fabric, this bed frame exudes elegance and comfort. Its tufted headboard adds a touch of sophistication, while the sturdy slat support system ensures durability and stability. Whether you're seeking a glamorous retreat or a cozy oasis, this tufted velvet bed frame provides the perfect blend of style and comfort for a restful night's sleep.",
		image: "https://i.ibb.co/zmFjWr1/Tufted-Velvet-Bed.jpg",
		id: 45,
		Rating: 4.4,
	},
	{
		name: "Floating Nightstand with Drawer",
		category: "Bedroom Furniture",
		subCategory: "Nightstands",
		trending: false,
		price: 150,
		description:
			"Introducing our Floating Nightstand with Drawer, a sleek and space-saving solution for your bedside essentials. Crafted with durable wood and featuring a minimalist design, this nightstand mounts effortlessly to the wall, creating a floating effect that adds modern flair to any bedroom. Its single drawer provides convenient storage for books, glasses, or other nighttime necessities, while the open shelf offers space for decorative accents or additional storage baskets. Whether used alone or paired with a matching bed frame, this floating nightstand adds both style and functionality to your bedroom decor.",
		image: "https://i.ibb.co/xqpDcBR/Floating-Nightstand-with-Drawer.jpg",
		id: 46,
		Rating: 4.5,
	},
	{
		name: "Mirrored Bedside Table",
		category: "Bedroom Furniture",
		subCategory: "Nightstands",
		trending: false,
		price: 200,
		description:
			"Introducing our Mirrored Bedside Table, a glamorous addition to your bedroom decor. Crafted with a sturdy wood frame and adorned with mirrored panels, this bedside table exudes elegance and sophistication. Its compact size makes it perfect for small spaces, while the mirrored finish adds a touch of luxury to any room. The single drawer offers convenient storage for nighttime essentials, while the tabletop provides space for a lamp, alarm clock, or decorative items. Whether used alone or paired with a matching bedroom set, this mirrored bedside table adds instant glamour to your sleeping sanctuary.",
		image: "https://i.ibb.co/wSWp4Bv/Mirrored-Bedside-Table.jpg",
		id: 47,
		Rating: 4.3,
	},
	{
		name: "Farmhouse Style Nightstand",
		category: "Bedroom Furniture",
		subCategory: "Nightstands",
		trending: false,
		price: 130,
		description:
			"Introducing our Farmhouse Style Nightstand, a charming addition to your bedroom decor. Crafted with durable wood and featuring a rustic farmhouse design, this nightstand exudes warmth and character. Its single drawer and open shelf provide convenient storage for nighttime essentials and decorative accents, while the distressed finish adds a touch of vintage charm. Whether used in a farmhouse-inspired bedroom or as an eclectic accent piece, this nightstand brings both style and functionality to your bedside.",
		image: "https://i.ibb.co/9T9tKs7/Farmhouse-Style-Nightstand.jpg",
		id: 48,
		Rating: 3.8,
	},
	{
		name: "Charging Station Nightstand",
		category: "Bedroom Furniture",
		subCategory: "Nightstands",
		trending: false,
		price: 180,
		description:
			"Introducing our Charging Station Nightstand, a modern and practical addition to your bedroom. Crafted with durable wood and featuring built-in USB ports and outlets, this nightstand allows for convenient device charging overnight. Its single drawer and open shelf provide storage space for essentials, while the sleek design complements any decor.",
		image: "https://i.ibb.co/FHFVxqt/Charging-Station-Nightstand.jpg",
		id: 49,
		Rating: 4,
	},
	{
		name: "Scandinavian Bedside Cabinet",
		category: "Bedroom Furniture",
		subCategory: "Nightstands",
		trending: false,
		price: 150,
		description:
			"Introducing our Scandinavian Bedside Cabinet, a minimalist and functional addition to your bedroom. Crafted with sturdy wood and featuring clean lines, this nightstand embodies Scandinavian design principles. Its single drawer offers storage for nighttime essentials, while the open shelf provides space for books or decorative items. With its sleek and versatile design, this bedside cabinet complements a variety of decor styles.",
		image: "https://i.ibb.co/Kq6q9XR/Scandinavian-Bedside-Cabinet.png",
		id: 50,
		Rating: 3.9,
	},
	{
		name: "Sliding Door Wardrobe",
		category: "Bedroom Furniture",
		subCategory: "Wardrobes",
		trending: true,
		price: 1000,
		description:
			"ccIntroducing our Sliding Door Wardrobe, a stylish and space-saving storage solution for your bedroom. Crafted with durable wood and featuring sleek sliding doors, this wardrobe offers ample space to store your clothing and accessories. Its modern design and smooth sliding mechanism make it perfect for rooms with limited space, while the interior shelves and hanging rails provide versatile storage options. Whether used in a contemporary or minimalist bedroom, this sliding door wardrobe combines functionality with elegance to meet your storage needs.c",
		image: "https://i.ibb.co/HFL8LcP/Sliding-Door-Wardrobe.png",
		id: 51,
		Rating: 4.6,
	},
	{
		name: "Freestanding Armoire",
		category: "Bedroom Furniture",
		subCategory: "Wardrobes",
		trending: false,
		price: 800,
		description:
			"Introducing our Freestanding Armoire, a classic and versatile storage solution for your bedroom. Crafted with durable wood and featuring a timeless design, this armoire offers ample space to organize your clothing, linens, and other essentials. Its freestanding design allows for easy placement in any room, while the interior shelves, drawers, and hanging rod provide versatile storage options. Whether used as a standalone piece or paired with other bedroom furniture, this freestanding armoire adds both style and functionality to your space.",
		image: "https://i.ibb.co/7JTwqrs/Freestanding-Armoire.png",
		id: 52,
		Rating: 4.8,
	},
	{
		name: "Built-In Closet Organizer",
		category: "Bedroom Furniture",
		subCategory: "Wardrobes",
		trending: false,
		price: 1300,
		description:
			"Introducing our Built-In Closet Organizer, a customizable storage solution for your bedroom. Crafted with durable materials and designed to fit seamlessly into your closet space, this organizer maximizes storage efficiency. Its modular design allows for customizable configurations, with shelves, drawers, hanging rods, and other accessories to suit your needs. Whether you're looking to optimize a small closet or create a custom wardrobe space, this built-in closet organizer offers both functionality and versatility to elevate your bedroom storage.",
		image: "https://i.ibb.co/Pr1r0bM/Built-In-Closet-Organizer.png",
		id: 53,
		Rating: 4.7,
	},
	{
		name: "Corner Wardrobe Unit",
		category: "Bedroom Furniture",
		subCategory: "Wardrobes",
		trending: false,
		price: 900,
		description:
			"Introducing our Corner Wardrobe Unit, a space-saving and stylish storage solution for your bedroom. Crafted with durable wood and designed to fit snugly into a corner, this wardrobe unit maximizes storage potential in compact spaces. Its versatile design features a combination of shelves, drawers, and hanging rods, providing ample space to organize your clothing and accessories. Whether you're looking to optimize an unused corner or create a custom storage solution, this corner wardrobe unit combines functionality with elegance to enhance your bedroom decor.",
		image: "https://i.ibb.co/XXYWXM7/Corner-Wardrobe-Unit.png",
		id: 54,
		Rating: 4.5,
	},
	{
		name: "Kids' Wardrobe with Drawers",
		category: "Bedroom Furniture",
		subCategory: "Wardrobes",
		trending: false,
		price: 400,
		description:
			"Introducing our Kids' Wardrobe with Drawers, a charming and practical storage solution for your child's bedroom. Crafted with durable materials and designed with kids in mind, this wardrobe features a combination of hanging rods and drawers, providing ample space for clothing and accessories. Its child-friendly design includes rounded edges and easy-to-open drawers, ensuring safety and convenience for young users. Whether used alone or paired with other kids' furniture, this wardrobe adds both style and functionality to your child's bedroom.",
		image: "https://i.ibb.co/qsKbsZp/Kids-Wardrobe-with-Drawers.jpg",
		id: 55,
		Rating: 4.3,
	},
	{
		name: "Aluminum Dining Set with Umbrella",
		category: "Outdoor Furniture",
		subCategory: "Patio Sets",
		trending: false,
		price: 1000,
		description:
			"Introducing our Aluminum Dining Set with Umbrella, the perfect addition to your outdoor space. Crafted with durable aluminum frames, this set includes a table, chairs, and a matching umbrella for added comfort. Whether hosting a barbecue or enjoying a family meal outdoors, this dining set combines style and functionality for your patio or deck.",
		image: "https://i.ibb.co/xSS1R9T/Aluminum-Dining-Set-with-Umbrella.jpg",
		id: 56,
		Rating: 4.1,
	},
	{
		name: "Wicker Conversation Set",
		category: "Outdoor Furniture",
		subCategory: "Patio Sets",
		trending: false,
		price: 600,
		description:
			"Introducing our Wicker Conversation Set, ideal for relaxing and entertaining in your outdoor space. Crafted with durable wicker material, this set includes comfortable chairs and a coffee table, perfect for intimate gatherings or quiet moments outdoors. The stylish design adds elegance to your patio or deck, while the weather-resistant construction ensures long-lasting enjoyment. Whether enjoying morning coffee or evening conversations, this wicker conversation set creates a cozy retreat in your outdoor oasis.",
		image: "https://i.ibb.co/PTjBVMG/Wicker-Conversation-Set.jpg",
		id: 57,
		Rating: 4,
	},
	{
		name: "Adirondack Chairs and Side Table",
		category: "Outdoor Furniture",
		subCategory: "Patio Sets",
		trending: false,
		price: 400,
		description:
			"Introducing our Adirondack Chairs and Side Table set, a timeless addition to your outdoor relaxation space. Crafted with durable wood or weather-resistant materials, these classic Adirondack chairs offer comfort and style for lounging outdoors. The matching side table provides a convenient surface for drinks, snacks, or books. Whether placed on a patio, deck, or by the pool, this set invites you to unwind and enjoy the beauty of nature in comfort and style.",
		image: "https://i.ibb.co/DC430Qd/Adirondack-Chairs-and-Side-Table.jpg",
		id: 58,
		Rating: 4.2,
	},
	{
		name: "Folding Bistro Set",
		category: "Outdoor Furniture",
		subCategory: "Patio Sets",
		trending: false,
		price: 200,
		description:
			"Introducing our Folding Bistro Set, perfect for cozy outdoor dining or relaxation. Crafted with lightweight yet sturdy materials, this set includes a bistro table and two folding chairs. The compact design makes it ideal for small spaces such as balconies, patios, or even picnics in the park. When not in use, the chairs conveniently fold for easy storage. Whether enjoying a morning coffee or a glass of wine at sunset, this bistro set adds charm and functionality to your outdoor experience.		",
		image: "https://i.ibb.co/6nJPQFD/Folding-Bistro-Set.jpg",
		id: 59,
		Rating: 4.1,
	},
	{
		name: "Sectional Sofa Set with Fire Pit",
		category: "Outdoor Furniture",
		subCategory: "Patio Sets",
		trending: true,
		price: 2500,
		description:
			"Introducing our Sectional Sofa Set with Fire Pit, the ultimate outdoor lounge experience. Crafted with weather-resistant materials, this set features a spacious sectional sofa and a built-in fire pit table. Perfect for entertaining or cozy evenings with loved ones, the sectional offers ample seating space while the fire pit provides warmth and ambiance. Whether hosting a barbecue or roasting marshmallows under the stars, this sectional sofa set with fire pit transforms your patio into a luxurious retreat for relaxation and socializing.",
		image: "https://i.ibb.co/0nvxK9D/Sectional-Sofa-Set-with-Fire-Pit.jpg",
		id: 60,
		Rating: 4.4,
	},
	{
		name: "Adjustable Chaise Lounge Chairs",
		category: "Outdoor Furniture",
		subCategory: "Sun Loungers",
		trending: false,
		price: 500,
		description:
			"Introducing our Adjustable Chaise Lounge Chairs, perfect for soaking up the sun in comfort and style. Crafted with durable materials, these lounge chairs feature adjustable backrests, allowing you to find the perfect reclining position for relaxation. The weather-resistant construction makes them ideal for outdoor use, whether by the poolside, on the patio, or in the garden. With their sleek design and ergonomic comfort, these adjustable chaise lounge chairs offer a luxurious lounging experience for enjoying sunny days outdoors.",
		image: "https://i.ibb.co/0GGxcxx/Adjustable-Chaise-Lounge-Chairs.png",
		id: 61,
		Rating: 4.8,
	},
	{
		name: "Teak Wood Sun Lounger",
		category: "Outdoor Furniture",
		subCategory: "Sun Loungers",
		trending: false,
		price: 500,
		description:
			"Introducing our Teak Wood Sun Lounger, a timeless and elegant addition to your outdoor relaxation space. Crafted from high-quality teak wood, this sun lounger offers both durability and natural beauty. Its adjustable backrest allows for personalized comfort, while the sturdy construction ensures stability. Whether soaking up the sun by the pool or enjoying a quiet afternoon in the garden, this teak wood sun lounger provides a luxurious and comfortable lounging experience.",
		image: "https://i.ibb.co/6w6tsxZ/Teak-Wood-Sun-Lounger.png",
		id: 62,
		Rating: 4.6,
	},
	{
		name: "Inflatable Poolside Lounger",
		category: "Outdoor Furniture",
		subCategory: "Sun Loungers",
		trending: true,
		price: 50,
		description:
			"Introducing our Inflatable Poolside Lounger, the perfect companion for sunny days by the pool. Crafted with durable and waterproof materials, this lounger inflates quickly and easily for instant relaxation. Its ergonomic design and built-in pillow provide comfort while lounging, and the compact size makes it convenient for storage and transport. Whether floating in the pool or soaking up the sun on the deck, this inflatable poolside lounger offers a fun and comfortable way to enjoy outdoor relaxation.",
		image: "https://i.ibb.co/jDswknD/Inflatable-Poolside-Lounger.png",
		id: 63,
		Rating: 4.5,
	},
	{
		name: "Double Hammock with Stand",
		category: "Outdoor Furniture",
		subCategory: "Sun Loungers",
		trending: false,
		price: 300,
		description:
			"Introducing our Double Hammock with Stand, the epitome of outdoor relaxation. Crafted with durable materials, this hammock provides a comfortable and cozy spot for two to unwind. The included stand offers easy setup and versatility, allowing you to place the hammock anywhere in your outdoor space without the need for trees or posts. Whether enjoying a lazy afternoon nap or stargazing under the night sky, this double hammock with stand provides a luxurious and serene lounging experience.",
		image: "https://i.ibb.co/bNSr3D9/Double-Hammock-with-Stand.png",
		id: 64,
		Rating: 4.2,
	},
	{
		name: "Zero Gravity Reclining Chair",
		category: "Outdoor Furniture",
		subCategory: "Sun Loungers",
		trending: true,
		price: 130,
		description:
			"Introducing our Zero Gravity Reclining Chair, the ultimate in outdoor relaxation. Crafted with a sturdy steel frame and breathable fabric, this chair offers unparalleled comfort and support. Its innovative zero gravity design allows you to recline into a weightless position, relieving pressure on your joints and providing maximum relaxation. The adjustable headrest and detachable tray add convenience and versatility, while the foldable design makes it easy to transport and store. Whether lounging by the pool or camping under the stars, this zero gravity reclining chair offers a luxurious and rejuvenating outdoor experience.",
		image: "https://i.ibb.co/CWXTGbp/Zero-Gravity-Reclining-Chair.png",
		id: 65,
		Rating: 4.3,
	},
	{
		name: "All-Weather Wicker Sofa",
		category: "Outdoor Furniture",
		subCategory: "Outdoor Sofas",
		trending: false,
		price: 800,
		description:
			"Introducing our All-Weather Wicker Sofa, a stylish and durable seating option for your outdoor space. Crafted with high-quality wicker material that is resistant to fading, cracking, and weathering, this sofa is built to withstand the elements year-round. Its spacious design provides ample seating for family and friends, while the plush cushions offer comfort and support. Whether used on a patio, deck, or in a sunroom, this all-weather wicker sofa adds charm and functionality to any outdoor setting.",
		image: "https://i.ibb.co/858bfyB/All-Weather-Wicker-Sofa.jpg",
		id: 66,
		Rating: 4,
	},
	{
		name: "Aluminum Framed Patio Sofa",
		category: "Outdoor Furniture",
		subCategory: "Outdoor Sofas",
		trending: true,
		price: 900,
		description:
			"Introducing our Aluminum Framed Patio Sofa, the perfect blend of style and durability for your outdoor living space. Crafted with a lightweight yet sturdy aluminum frame, this sofa is built to withstand the elements while providing comfortable seating for outdoor relaxation. Its sleek design and neutral cushions complement any outdoor decor, while the spacious seating area accommodates family and guests with ease. Whether used on a patio, deck, or poolside, this aluminum framed patio sofa offers both comfort and elegance for outdoor lounging.",
		image: "https://i.ibb.co/yPMKct2/Aluminum-Framed-Patio-Sofa.jpg",
		id: 67,
		Rating: 4.5,
	},
	{
		name: "Modular Outdoor Sectional Sofa",
		category: "Outdoor Furniture",
		subCategory: "Outdoor Sofas",
		trending: false,
		price: 1500,
		description:
			"Introducing our Modular Outdoor Sectional, a versatile and stylish seating solution for your outdoor space. Crafted with durable materials designed to withstand the elements, this sectional offers customizable configuration options to suit your needs. Its modular design allows you to arrange the pieces to create different seating arrangements, perfect for entertaining or lounging. The plush cushions provide comfort and support, while the sleek design adds a modern touch to your patio or deck. Whether hosting a barbecue or relaxing in the sun, this modular outdoor sectional offers comfort and versatility for outdoor living.",
		image: "https://i.ibb.co/3vQ7Mbt/Modular-Outdoor-Sectional.jpg",
		id: 68,
		Rating: 4.6,
	},
	{
		name: "Acacia Wood Outdoor Couch",
		category: "Outdoor Furniture",
		subCategory: "Outdoor Sofas",
		trending: true,
		price: 700,
		description:
			"Introducing our Acacia Wood Outdoor Couch, a blend of natural beauty and durability for your outdoor oasis. Crafted from sturdy acacia wood known for its weather-resistant properties, this couch is built to withstand outdoor conditions while retaining its elegant appearance. Its spacious seating and plush cushions offer comfort for lounging or entertaining guests. Whether placed on a patio, deck, or garden, this acacia wood outdoor couch adds warmth and charm to any outdoor setting.",
		image: "https://i.ibb.co/C661Jzs/Acacia-Wood-Outdoor-Couch.jpg",
		id: 69,
		Rating: 4.5,
	},
	{
		name: "Loveseat Glider Bench",
		category: "Outdoor Furniture",
		subCategory: "Outdoor Sofa",
		trending: false,
		price: 300,
		description:
			"Introducing our Loveseat Glider Bench, the epitome of comfort and relaxation for your outdoor space. Crafted with durable materials designed to withstand the elements, this bench features a gentle gliding motion that adds a soothing touch to any outdoor setting. Its compact size makes it ideal for smaller patios or gardens, while the comfortable seating provides a cozy spot for two to enjoy the beauty of nature. Whether placed on a porch, patio, or in a garden nook, this loveseat glider bench offers a charming and inviting seating option for outdoor lounging.",
		image: "https://i.ibb.co/smSfn6K/Loveseat-Glider-Bench.jpg",
		id: 70,
		Rating: 4.1,
	},
];
